### ISSUE TITLE
浏览器的支持情况咋样

### ISSUE THREAD

**Issue by fyddaben** [Tencent/westore#1]
一直想用这样的插件，但是考虑到浏览器的支持情况，希望可以有个说明

**Comment by jinwei233** [comment]
大致浏览下源码，利用 `defineProperty`这个方法，所以 IE 8 以下应该是不可以了

**Comment by dntzhang** [comment]
是啊。还用了个Array.prototype.forEach而已~~  @fyddaben @WeweTom

**Comment by hafeyang** [comment]
IE8以上浏览器都有自带的observe了。还需要这100多行代码的封装么？
