### ISSUE TITLE
westore能否实现类似手写emit这种发布订阅模式？

### ISSUE THREAD

**Issue by linlinNB** [Tencent/westore#100]
场景：需要做一个全局通知，长连接获取数据，放入store中，在某一个page当中，store.onChange这个方法能否达到类似效果？

**Comment by dntzhang** [comment]
自己引用下 mitt 库去做 https://github.com/developit/mitt

**Comment by dntzhang** [comment]
westore 不集成这个功能

**Comment by linlinNB** [comment]
@dntzhang 好的，了解了。谢谢指点
