### ISSUE TITLE
update更新算法出现异常，每次返回上一页在进入就变成了这样

### ISSUE THREAD

**Issue by Marla62** [Tencent/westore#105]
![7f9002f81d4ff9f8ddc3c83b15bbd5b](https://user-images.githubusercontent.com/34474822/77066226-bb77ae00-6a1d-11ea-9ce9-30fb179c2f6a.png)
请看图片。我的menuVoList只有一个分类 为什么左侧可以渲染6个分类出来

**Comment by kevinroy-lo** [comment]
请问解决了吗？我也有类似的问题出现。

**Comment by Marla62** [comment]
解决了，应该是给diff加key解决的
