### ISSUE TITLE
一点疑问，能否渐进式地接入此框架？

### ISSUE THREAD

**Issue by Hangeer** [Tencent/westore#135]
看了源码，相关以及issue，提出自己的一点疑问：

【背景】
希望小程序中，部分数据能通过westore的形式，进行共享。但受限于当前已经写好的代码，短期内将页面推翻，使用westore的形式重新开发，成本是比较高的

【尝试】
因此尝试，将原有page.data中的一部分（某几个属性，非全量data），交给westore接管，逐渐迁移
子组件通过调用store实例的方法，也能修改页面的数据

但发现了问题：westore的store.data一定要与page.data强绑定起来，没法只绑定部分data
原因是：内部在做diff的时候，所用数据是基于整个页面的data（store.data与之前的page.data）进行diff，再将这个diff更新到页面数据中

【问题】
1. 想请问下，页面中只接入部分data的场景有解吗？
2. 看到有个omix的解决方案，想参考下，不过链接基本上都打不开了（在 微信开发者社区、掘金、以及此issue中），想知道最新的链接

多谢

**Comment by JohnieXu** [comment]
这个问题不错，也想知道+1

**Comment by dntzhang** [comment]
omix 链接在这里 https://github.com/Tencent/omi/tree/v6/packages/omix  

不过更推荐 westore
