### ISSUE TITLE
如何多个页面共享一个store使用

### ISSUE THREAD

**Issue by nanhupatar** [Tencent/westore#142]
目前尝试了bind相同的viewkey，不行。请问有什么方式能跨页面使用吗

**Comment by nanhupatar** [comment]
@dntzhang

**Comment by nanhupatar** [comment]
目前解决方案 ,可以实现多个页面绑定同一store，暂不清楚有什么弊端
	onShow() {
		this.setData({ ...Store.data }, () => {
			Store.bind('page', this);
		});
	},
```

**Comment by dntzhang** [comment]
1.你可以先new 出来再import到 各个store

2.westore 没有斩断 store 之间的通讯吧，这个可以开发者自己组织依赖关系、发布订阅什么的。

model之间可以多对多互相依赖，store之间可以多对多互相依赖，model和store之间可以多对多互相依赖。

westore只是斩断model和view之间的依赖。

**Comment by Megasu** [comment]
## 请问官方能出多个页面共享一个 store 例子吗？

现在官方的 example 只是在一个页面中用到 store，这样的 store 抽离在**单个页面中**使用感觉是**非必须**的。
但 原生小程序的多个页面共享一个 store 的需求应该**更常见**，多页面共享用户信息，共享购物车数量等。

所以冒昧问一下，官方是否有计划出品类似 pinia , vuex 这类全局状态管理库，方便使用原生小程序的开发者使用。🌹🌹

**Comment by wuhao1477** [comment]
> ## 请问官方能出多个页面共享一个商店的例子吗？
> 现在官方的例子只是在一个页面中可用存储，这样的存储抽离在**单个页面中**使用感觉**是非**必须的。 但初期小程序的多个页面共享一个存储的需求应该**更常见**，多页面共享用户信息，共享购物车数量等。
> 
> 所以冒昧问一下，官方是否有计划出品类似 pinia , vuex 这类全局状态管理库，方便使用简单小程序的开发者使用。🌹🌹

请问一下“多页面共享用户信息，共享购物车数量”等需求的话目前您的解决方案用的是什么呢？
