### ISSUE TITLE
可以使data支持计算属性吗

### ISSUE THREAD

**Issue by zjy2931** [Tencent/westore#17]
。。。。比较懒。。

**Comment by dntzhang** [comment]
具体点？什么是计算属性

**Comment by zjy2931** [comment]
类似这样的  this.data.name = function (){
      return “my_name";
}
使用
<view>{{name}}</view>

**Comment by dntzhang** [comment]
多谢，下午试试

**Comment by dntzhang** [comment]
已经支持，通过前置 $ 来绑定：
```js
<view>{{$fullName}}</view>
```

**Comment by dntzhang** [comment]
@zjy2931

**Comment by zjy2931** [comment]
哇 我去试试

**Comment by zjy2931** [comment]
重写 get方法会不会更好一点
![](https://ws1.sinaimg.cn/large/c2e8730ely1fvqj2qh1anj20h209rq3s.jpg)

**Comment by dntzhang** [comment]
已改，赞。

**Comment by zjy2931** [comment]
现在的问题是  不能在store外定义  函数属性   函数属性只能写在store文件内，能改吗

**Comment by dntzhang** [comment]
page或组件上的 data 上也能定义吧？！

**Comment by dntzhang** [comment]
store.xxx = function(){}  可以动态改是吗？

**Comment by zjy2931** [comment]
是呢

**Comment by zjy2931** [comment]
![](https://ws1.sinaimg.cn/large/c2e8730ely1fvreuh1h7cj20cn04r0t0.jpg)
这样写  list 是没有重写get函数的吧
![](https://ws1.sinaimg.cn/large/c2e8730ely1fvreyl7m35j204x069wek.jpg)

**Comment by dntzhang** [comment]
我来试试写下defineProperty的 set

**Comment by dntzhang** [comment]
@zjy2931 这样肯定不行，因为没有监控所有 get 和 set，只监控了以前是函数的

**Comment by zjy2931** [comment]
所以在update函数里 需要重新过滤函数属性的

**Comment by zjy2931** [comment]
或者是  给store一个独立属性 专门处理函数属性  映射到 store的data属性上

**Comment by dntzhang** [comment]
你再 create.js 66 行加入
```js
 exceDataFn(globalStore.data)
```

**Comment by zjy2931** [comment]
我不会写这些东西  只能提点建议咯

**Comment by zjy2931** [comment]
这样是可以的 但是每次都要全遍历一次  应该可以优化下

**Comment by dntzhang** [comment]
恩。我先提交，仅仅遍历一层，且只判断是函数的话很快的。

**Comment by dntzhang** [comment]
动态的函数属性需要使用 store.method 了。
store.method(path, fn) 更新或扩展函数属性，注意这里不能直接赋值的方式修改函数属性，需要使用 store.method
