### ISSUE TITLE
这种是什么情况，组件内data获取不到

### ISSUE THREAD

**Issue by zjy2931** [Tencent/westore#24]
![](http://ww1.sinaimg.cn/large/c2e8730ely1fvw9v10l4dj20bz075dga.jpg)
这两个打印的少一个属性
![](https://ws1.sinaimg.cn/large/c2e8730ely1fvw9w5skd2j20h508nt99.jpg)
getName 属性通过this.data 获取不到。。。

**Comment by dntzhang** [comment]
不是同一 data 啊，很正常。有需要获取的场景吗？

```js
this.store.data.abc ='abcaa'
console.log(this.data.abc) //undefined
```

**Comment by zjy2931** [comment]
不是那个问题，
![](https://ws1.sinaimg.cn/large/c2e8730ely1fvwcz6ze1kj20ae055weo.jpg)
this.data 的结果
![](https://ws1.sinaimg.cn/large/c2e8730ely1fvwd00kvq8j205103lglj.jpg)
这里面直接设置属性都没问题，添加函数属性是获取不到的

**Comment by zjy2931** [comment]
![](https://ws1.sinaimg.cn/large/c2e8730ely1fvwd2xy2f7j20bw07i0t2.jpg)
这样重复更新两次 就没问了
![](https://ws1.sinaimg.cn/large/c2e8730ely1fvwd3ss6ocj205d03dgli.jpg)

**Comment by dntzhang** [comment]
修复了，多谢 @zjy2931  https://github.com/dntzhang/westore/commit/611dee68016c9bb2544be28e8e337b10a82c8512

**Comment by zjy2931** [comment]
好,神速

**Comment by zjy2931** [comment]
问一个问题，这样初始化页面，感觉是把store的data全部挂在page的data上了,很多当前页面无用的数据也挂载在page的data上，数据量太大的话不会出问题吗

**Comment by zjy2931** [comment]
create（store，options），这里的store每个页面传入的都一样吗

**Comment by dntzhang** [comment]
1.不会出问题，纯组件记得使用 Component 不使用 create。

2.每个页面传入一样

**Comment by zjy2931** [comment]
好的，thanks

**Comment by dntzhang** [comment]
如果想使用 this.update 的话，纯组件也可以使用  create({pure:true}) 的方式。
