### ISSUE TITLE
这种现象是正常现象吗？

### ISSUE THREAD

**Issue by zjy2931** [Tencent/westore#25]
原来的data 有一项 userInfo

![](https://ws1.sinaimg.cn/large/c2e8730ely1fw0y9q5darj20mq00tjra.jpg)

我通过  store.data =  new_data
new data  有一项  userInfo
![](https://ws1.sinaimg.cn/large/c2e8730ely1fw0ybw3mmlj205n00rq2p.jpg)
 通过update更新后 
数据结构变成 这样

![](https://ws1.sinaimg.cn/large/c2e8730ely1fw0yd74ii1j20n2014wed.jpg)

diff并没有把userInfo更新成空，而是把其中的每个属性都变成空了，我觉得这样逻辑是不对的，使用起来也有问题

**Comment by dntzhang** [comment]
正在修

**Comment by zjy2931** [comment]
这个 参考一下其他人的  json diff 应该会少很多坑

**Comment by zjy2931** [comment]
反正我不懂，等大佬更新 =-

**Comment by dntzhang** [comment]
@zjy2931 已经没坑了~~~

**Comment by zjy2931** [comment]
好

**Comment by zjy2931** [comment]
这样就出新的问题了。。。。
···
this.update()
```
方法会报错

**Comment by zjy2931** [comment]
![](https://ws1.sinaimg.cn/large/c2e8730ely1fw10dvrmlzj20mx07j3zs.jpg)

**Comment by dntzhang** [comment]
...，等我吃完饭回去看下。setdata传了空path

**Comment by zjy2931** [comment]
好

**Comment by dntzhang** [comment]
@zjy2931 改好了~~

**Comment by zjy2931** [comment]
好的 昨天看到了
