### ISSUE TITLE
能否支持一些全局data及函数

### ISSUE THREAD

**Issue by xmsz** [Tencent/westore#27]
**使用场景：**
例如用户信息（userInfo），信息这个基本上每个页面都用的到
而目前使用的是局部更新，就必须要在每个页面的data里再输入一次，有点繁琐

**解决方案：**
支持局部更新下
定义全局的data和函数

**Comment by dntzhang** [comment]
只要全局data变更，更新所有页面和组件？

**Comment by xmsz** [comment]
就是在updateAll：false的情况下

store文件有个数据
```
data: {
user_info: {}
}
```


页面a
也必须在data里声明，才能保持更新状态
```
data: {
user_info: {}
}

```
---

但实际上这个`user_info`在页面B、页面C、页面...都会用到
那目前的情况是，我必须得在这这些页面声明一遍哈

---

**Comment by dntzhang** [comment]
明白了。我想想怎么搞

**Comment by zjy2931** [comment]
是不是增加个updateAll的方法  更新数据的时候 可以选择使用局部的更新 还是全局的更新
其实没必要区分局部和全局吧  局部更新视图  直接用小程序的SETdata方法不更好吗

**Comment by dntzhang** [comment]
setData还是有局限性。比如:

this.setData('xxx.xx.xx',{超级大的JSON})  这里居然不会 diff。使用 update 会diff

打算store下新增一个：

globalData:['userInfo','xxx.xx','xxx[1]' ]  

或者加个 updateAllPage 方法？看下哪个好~~

@zjy2931 @xmsz

**Comment by dntzhang** [comment]
globalData 好一些？只需要配一次，不用动脑是 调用 updateAllPage  还是 update

**Comment by dntzhang** [comment]
https://github.com/dntzhang/westore/commit/0e2cd038a3b60c4a947d9413f698029a48722f82 已提交

**Comment by zjy2931** [comment]
> setData还是有局限性。比如:
> 
> this.setData('xxx.xx.xx',{超级大的JSON}) 这里居然不会 diff。使用 update 会diff
> 
> 打算store下新增一个：
> 
> globalData:['userInfo','xxx.xx','xxx[1]' ]
> 
> 或者加个 updateAllPage 方法？看下哪个好~~
> 
> @zjy2931 @xmsz

因为他只是局部使用 根本不用diff  第一，数量不好太大，第二，diff完也还是这么多数据
如果是全局的 他又没必要用 setData方法 所以 没什么问题

**Comment by zjy2931** [comment]
> > setData还是有局限性。比如:
> > this.setData('xxx.xx.xx',{超级大的JSON}) 这里居然不会 diff。使用 update 会diff
> > 打算store下新增一个：
> > globalData:['userInfo','xxx.xx','xxx[1]' ]
> > 或者加个 updateAllPage 方法？看下哪个好~~
> > @zjy2931 @xmsz
> 
> 因为他只是局部使用 根本不用diff 第一，数量不好太大，第二，diff完也还是这么多数据
> 如果是全局的 他又没必要用 setData方法 所以 没什么问题

我是这么认为的，对我来说 前面哪些就够用了 后面加的云数据库操作 根本用不到，而且代码的健壮性和容错性太低了，太着急了

**Comment by dntzhang** [comment]
云数据库对现有 API 没有影响
