### ISSUE TITLE
原有小程序如果想迁移的话  工作量会不会比较庞大 页面大概有 15个左右 不算组件的

### ISSUE THREAD

**Issue by HZZformGD** [Tencent/westore#29]
原有小程序如果想迁移的话  工作量会不会比较庞大 页面大概有 15个左右 不算组件的

**Comment by dntzhang** [comment]
关键看以前代码写得怎么样哈，写得越好迁移越快

**Comment by HZZformGD** [comment]
@dntzhang  哈哈哈 这个回答满分  挺想迁移的 但是时间又不多 线上产品又怕 迁完后期bug

**Comment by dntzhang** [comment]
所以尽量用在新项目上吧

**Comment by HZZformGD** [comment]
好的 多谢你们的贡献啊 我已经star 了 就不再点多一次star了 （斜眼笑.jpg）
