### ISSUE TITLE
westore-cloud里调用this.update()出错

### ISSUE THREAD

**Issue by lentg** [Tencent/westore#35]
![image](https://user-images.githubusercontent.com/198310/47360422-12caff00-d702-11e8-85c5-38cf9c1ea5d5.png)

**Comment by dntzhang** [comment]
这个要把util的create.js替换成新的

**Comment by dntzhang** [comment]
刚提交了

**Comment by lentg** [comment]
> 刚提交了

下载最新的，还是无法运行
store里的env已更改

**Comment by dntzhang** [comment]
报什么错

**Comment by lentg** [comment]
> 报什么错

![image](https://user-images.githubusercontent.com/198310/47363702-ffbc2d00-d709-11e8-9539-61faaca573d2.png)

**Comment by lentg** [comment]
> > 报什么错
> 
> ![image](https://user-images.githubusercontent.com/198310/47363702-ffbc2d00-d709-11e8-9539-61faaca573d2.png)

![image](https://user-images.githubusercontent.com/198310/47363797-46118c00-d70a-11e8-9fc0-be73e0deb277.png)

**Comment by lentg** [comment]
我的微信号    lentxg

**Comment by dntzhang** [comment]
数据表建了吗？测试数据插入了吗

**Comment by lentg** [comment]
插入测试正常

**Comment by dntzhang** [comment]
数据表建了吗？测试数据插入了吗

**Comment by lentg** [comment]
插入product没任何问题

**Comment by dntzhang** [comment]
刚把 store里加了 `updateAll : true` ，测试 ok
