### ISSUE TITLE
近期chrome发布了 50.0.2661.75 (64-bit)，数据监听无法使用，之前的49版本是可以了

### ISSUE THREAD

**Issue by diserdong** [Tencent/westore#4]

**Comment by dntzhang** [comment]
额。我这更新失败。  @diserdong   报什么错？

**Comment by dntzhang** [comment]
![109c121d-8ad8-4f4a-9f08-a9deddca489f](https://cloud.githubusercontent.com/assets/7917954/14631441/ff865d70-0645-11e6-8bba-5cb78265115d.png)
刚试了。没有报错。 @diserdong 
![4cb4483b-93aa-4ff9-9e35-22e356f6fc06](https://cloud.githubusercontent.com/assets/7917954/14631450/0da16df0-0646-11e6-88f9-e4bc99ddd309.png)

**Comment by gafish** [comment]
Chrome50版本不再支持原生的 Object.observe 方法

**Comment by jddy** [comment]
@gafish  这是个bug 还是啥意思？ 为什么不支持？

**Comment by dntzhang** [comment]
@gafish  @jddy  @diserdong 
是不，不再支持。但是 observejs 没有使用 Object.observe。所以对本类库应该没啥影响~~
