### ISSUE TITLE
请教一下，使用wx.redirectTo 跳转页面之后 update() 就不会更新视图了

### ISSUE THREAD

**Issue by gexin1** [Tencent/westore#42]

**Comment by gexin1** [comment]
在a页面修改数据之后，
使用redirectTo跳转到b页面 
b页面 store里边的数据是a页面修改过的
但是b页面没有更新视图  
需要使用setDate重新更新视图吗 ？

**Comment by dntzhang** [comment]
稍等，我试下 wx.redirectTo

**Comment by dntzhang** [comment]
刚试了 wx.redirectTo 之后是可以 通过  this.update 更新视图的

**Comment by dntzhang** [comment]
你是不是忘记在 b 页面的 data 声明依赖了？

**Comment by gexin1** [comment]
wechatide://minicode/CDXOYAmb7F3v   请看下我的代码片段

**Comment by dntzhang** [comment]
刚提交修复了。你拉去最新。多谢 @gexin1
