### ISSUE TITLE
update方法缺乏回调功能

### ISSUE THREAD

**Issue by aeroxy** [Tencent/westore#45]
可以用将setData的方法promisify然后promise.all所有update产生的setData，但是可能对性能的影响较大。我改了以后会测一下，如果性能还行会发一个pull request。

**Comment by dntzhang** [comment]
好，等我围观下~~

**Comment by aeroxy** [comment]
嗯，提交了，没有发现有明显的性能问题。https://github.com/Tencent/westore/pull/46

**Comment by aeroxy** [comment]
已经将update promisified. https://github.com/Tencent/westore/pull/48
