### ISSUE TITLE
fullName:function(){}什么时候会去执行

### ISSUE THREAD

**Issue by raochuan** [Tencent/westore#52]
fullName:function(){}什么时候会去执行

**Comment by dntzhang** [comment]
绑定到视图就会自动执行啊

**Comment by raochuan** [comment]
刚刚测试使用你的demo添加下面方法，全局未使用，编译的时候就有执行
fullNameTest: function () {
      console.log("--------fullNameTest")
},

**Comment by raochuan** [comment]
export default {
  data: {
    motto: 'Hello World',
    userInfo: {},
    hasUserInfo: false,
    canIUse: wx.canIUse('button.open-type.getUserInfo'),
    logs: [],
    b: { 
      arr: [{ name: '数值项目1' }] ,
      //深层节点也支持函数属性
      fnTest:function(){
        return this.motto.split('').reverse().join('')
      }
    },
    firstName: 'dnt',
    lastName: 'zhang',
    fullName: function () {
      // console.log("---------fullName", this.firstName + this.lastName)
      return this.firstName + this.lastName
    },
    fullNameTest: function () {
      console.log("--------fullNameTest")
    },
    pureProp: 'pureProp',
    globalPropTest: 'abc', //更改我会刷新所有页面,不需要再组件和页面声明data依赖
    ccc: { ddd: 1 } //更改我会刷新所有页面,不需要再组件和页面声明data依赖
  },
  globalData: ['globalPropTest', 'ccc.ddd'],
  logMotto: function () {
    console.log("----------123123",this.data.motto)
    return "我是测试123556"
  },
  //默认 false，为 true 会无脑更新所有实例
  //updateAll: true
}

**Comment by IceApriler** [comment]
@dntzhang fullName绑定到视图上默认显示空啊，只有依赖数据变化时才会更新，是这样么？为什么这么设计？

**Comment by dntzhang** [comment]
可能是第一次初始化没有计算fullName导致结果！

另外推荐westore进化版本：https://github.com/Tencent/omi/tree/master/packages/omi-mp-create

**Comment by IceApriler** [comment]
@dntzhang 进化版本和westore有什么区别么，能不能简单介绍一下？我看才这个才写没多久啊，我是要在c端项目中用的，不知道有没有稳定。还有，westore的fullname的问题能解决么？
