### ISSUE TITLE
小白求教，store中的data不会随页面卸载而重置吗

### ISSUE THREAD

**Issue by zhcode66** [Tencent/westore#54]
比如
* store.js里面
```javascript
data: {
    arr: []
}
```
* 页面index.js里面
```javascript
create(store,{
    data: {
        arr: null
    }
})
```
当arr添加元素后退出该页面，再进来之前添加的元素还在，不会重置为初始值
这是正常现象吗
#### 详细代码片段：https://developers.weixin.qq.com/s/LJwbWTmi7M35
ps：我知道arr放在页面的data中就行了，可我想用diff，只放页面data中更新时就不会经过diff了

**Comment by dntzhang** [comment]
正常，不会重置。要重置请手动重置（onShow onHide什么的）
