### ISSUE TITLE
diff数组时，如果数组元素被删除，diff会返回无更改，导致页面元素无法移除

### ISSUE THREAD

**Issue by zhengguorong** [Tencent/westore#57]
diff算法会把两个对象做比对，如果是增改是没问题的，但是如果是删除操作，diff算法就没法抓出被删除的元素了。

**Comment by dntzhang** [comment]
删除的会设置成 null 啊

**Comment by zhengguorong** [comment]
是我的问题，diff两对象时，第二参数和第一参数有引用关系，所以没diff出来。
现在先对参数二做个深拷贝，就可以解决了
