### ISSUE TITLE
一个项目里的页面能否混合使用westore创建的页面和原生的小程序页面

### ISSUE THREAD

**Issue by yz3358** [Tencent/westore#60]
我发现如果只有一部分使用westore创建的页面和组件，在运行时会出现一些错误。可以这样使用吗？如果可以，这样使用的时候有没有什么注意事项？

**Comment by hunshikan** [comment]
可以混合使用的

**Comment by yz3358** [comment]
但是我发现了一个奇怪的现象：

westore利用了globalData.store 来存储一个实例，然而我们的项目里也利用了这个key来存储对象。虽然完全不影响使用（这一点让我们感到非常困惑不解），但是出于稳定性的考虑，我们替换了原先的所有涉及调用“globalData.store”的函数。

但是这样会出现一个问题：当进入小程序的第一个页面时，如果该页面不使用westore的create方法来创建，那么，当跳转到使用westore的页面时，会出现convert circular content to JSON 这个错误。而当我们修改了编译模式，把使用westore的页面放在首位时，这个错误就不会出现了。

于是我们干脆把原本放在首位的页面，也用了westore来创建。这样又出现了第二个问题：从该页面调到原生页面时，会报call stack 超出限制的错误。

最神奇的是，我们刻意的把globalData.store 设为空对象，所有的问题都没有了。

这说明在混合使用页面的时候，是会出现一些问题的。

> 可以混合使用的

**Comment by dntzhang** [comment]
看下的项目 https://github.com/Tencent/omi/tree/master/packages/omi-mp-create

**Comment by yz3358** [comment]
> 看下的项目 https://github.com/Tencent/omi/tree/master/packages/omi-mp-create

所以现在是可以直接用这个取代westore了吗？

**Comment by dntzhang** [comment]
是的，可以的。

**Comment by yz3358** [comment]
> 是的，可以的。

多谢
