### ISSUE TITLE
scroll  滑动 data乱变化

### ISSUE THREAD

**Issue by iceshu** [Tencent/westore#62]

**Comment by dntzhang** [comment]
贴下代码~~

**Comment by dntzhang** [comment]
看下的项目 https://github.com/Tencent/omi/tree/master/packages/omi-mp-create

**Comment by iceshu** [comment]
ok我看下

**Comment by Przeblysk** [comment]
怎么不用上拉加载

**Comment by iceshu** [comment]
@Lxjazni7 我用的就是上拉加载。。
@dntzhang 我看了下 里面没diff的东西么 没有计算属性这些。store里的东西无法在页面渲染等
