### ISSUE TITLE
对象被添加了属性

### ISSUE THREAD

**Issue by clll7** [Tencent/westore#7]
对象会被加上了$observeProps、$observer属性，如何能使用只有原有的属性的对象
![image](https://cloud.githubusercontent.com/assets/6949822/18612615/51fd141e-7d91-11e6-9075-a9d1f839f2f3.png)

**Comment by dntzhang** [comment]
@clll7 
目前没有办法。observe前自己先克隆一份。

**Comment by clll7** [comment]
好的，thank you
