### ISSUE TITLE
关于update的性能问题，还有按需更新的一些疑问？

### ISSUE THREAD

**Issue by NidMo** [Tencent/westore#81]
大佬你说westore的性能解药有两种：纯组件和按需更新。
按需更新就是只要在store和page或组件中定义data后就实现按需更新？
然后有重置默认值的api吗？
还有我提一下建议，在sotre声明data后，又要在页面或组件中第二次声明依赖data，体验不太好，能不能把依赖的data都放在一个对象里（如：pageA），注入依赖的时候直接注入pageA，不用重复声明这么麻烦。

**Comment by NidMo** [comment]
还有大型小程序的store拆分方案。我用第二种方案拆分，那页面的data的路径该怎么写，还有数据更新是异步的该怎么操作

**Comment by NidMo** [comment]
我修改了create函数加多一个参数pageName
syncValues(store.data[pageName], option.data)
然后初始化的时候页面data能被store里的覆盖，但this.update并没有同步到页面中，应该还要修改那几个函数？

**Comment by dntzhang** [comment]
为啥不用 omix

https://github.com/Tencent/omi/tree/master/packages/omix

omix 是 westore 的进化版本，没有 diff，增加了 context、mitt 等优秀特性。

**Comment by NidMo** [comment]
> 为啥不用 omix
> 
> https://github.com/Tencent/omi/tree/master/packages/omix
> 
> omix 是 westore 的进化版本，没有 diff，增加了 context、mitt 等优秀特性。

还有进化版啊。。。。我才发现，我去看看文档，研究下先

**Comment by NidMo** [comment]
> 为啥不用 omix
> 
> https://github.com/Tencent/omi/tree/master/packages/omix
> 
> omix 是 westore 的进化版本，没有 diff，增加了 context、mitt 等优秀特性。

context是只能用于组件是吗？
context: {abc: 'hello'}

page.wxml

1.   `<component  value="{{abc}}"></component>`


2.   `<view>{{abc}}</view>`
是只能用第一种用法是吗

**Comment by dntzhang** [comment]
context 是用于页面组件树共享数据，page注入的context，在page的组件里可以使用 this.context 访问到。

**Comment by dntzhang** [comment]
https://github.com/Tencent/omi/blob/master/packages/omix/components/hello/hello.js#L20

**Comment by dntzhang** [comment]
https://github.com/Tencent/omi/blob/master/packages/omix/pages/index/index.js#L6-L10

**Comment by NidMo** [comment]
> context 是用于页面组件树共享数据，page注入的context，在page的组件里可以使用 this.context 访问到。

感觉还有有点不习惯这样的写法，还有中心化那种方案，页面拿数据都是要 store.xxx.xxx ? 我本身是想将页面的数据放在store上进行托管，但中心化的写法好像将数据都收归所有，而去中心化又不能将页面数据从页面中剥离，是不是我思想出现了问题啊

**Comment by dntzhang** [comment]
是的，你的思想出问题了。omix 不强制中心化或者去中心化，甚至混合一起使用！

**Comment by NidMo** [comment]
> 是的，你的思想出问题了。omix 不强制中心化或者去中心化，甚至混合一起使用！

果然思想出了问题，之前写的一个项目就是用Vuex做中心化状态管理，不过有mapState辅助函数减少取数据的重复和冗余，不用store.xxx.xxx这样取数据而已，那么问题来了omix有类似mapState的辅助函数吗

**Comment by dntzhang** [comment]
没有

**Comment by NidMo** [comment]
> 没有

this.oData 性能和this.update 一样优秀？还有问一下之前的store.onChange是去掉了是吗？

**Comment by dntzhang** [comment]
this.oData 比 this.update 快，因为没有diff。onChange去掉了

**Comment by NidMo** [comment]
> this.oData 比 this.update 快，因为没有diff。onChange去掉了

this.oData 更新视图的条件是什么？
我写了段代码，this.oData 没有同步更新到视图上
page.js

methodA(show){
this.oData.show = show
}

methodB(show){
this.oData.show = show
}

A函数中this.oData 是有效的，能更新到视图。
但B函数就不行了，很奇怪，我输出this  发现this.oData.show  是有改变的，但AppData的数据节点树中的show就是没改变。
A函数是组件click触发的。
B函数是组件current改变的时候触发的。

**Comment by dntzhang** [comment]
B函数是组件current改变的时候触发的
----

这个是什么意思？

**Comment by NidMo** [comment]
> ## B函数是组件current改变的时候触发的
> 这个是什么意思？

就是B函数是组件的某个值改变的时候触发的

**Comment by dntzhang** [comment]
贴下相关代码

**Comment by NidMo** [comment]
> 贴下相关代码

![image](https://user-images.githubusercontent.com/24955673/56111724-8b14cd80-5f8b-11e9-8732-3cb57333bd38.png)
tabClick是A函数
![image](https://user-images.githubusercontent.com/24955673/56111755-9d8f0700-5f8b-11e9-83a3-6bea3b525c12.png)
tabChange是B函数

**Comment by dntzhang** [comment]
不明觉厉。和这个有关系吗？ https://github.com/Tencent/westore#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9

**Comment by dntzhang** [comment]
tabChange 有触发吗？ 更新视图是异步的，是不是被你后续的交互覆盖了 data？ debug下 omix 源码，或者打个 zip 包，把源码发给他 2498946845（qq）

**Comment by NidMo** [comment]
> tabChange 有触发吗？ 更新视图是异步的，是不是被你后续的交互覆盖了？

tabChange有触发啊，顺利进入下面的函数
![image](https://user-images.githubusercontent.com/24955673/56112447-ba2c3e80-5f8d-11e9-9f27-96b39cdf551f.png)

我把this.oData的代码换回setData是没有问题，视图有正常更新

**Comment by dntzhang** [comment]
代码打个zip发一下

**Comment by NidMo** [comment]
> 代码打个zip发一下

加了你qq了

**Comment by dntzhang** [comment]
https://github.com/Tencent/omi/commit/60ac4f4678a77fa95870c0203e24a463f0d17487

**Comment by NidMo** [comment]
> [Tencent/omi@60ac4f4](https://github.com/Tencent/omi/commit/60ac4f4678a77fa95870c0203e24a463f0d17487)

你那边测试是正常的？我拉了代码，没有变化啊。tabChange 里面的this.oData 还是没有同步到视图

**Comment by dntzhang** [comment]
https://github.com/Tencent/omi/commit/2163e38344d737c45abf2dcecf7a0521b088c9bd

**Comment by NidMo** [comment]
> [Tencent/omi@2163e38](https://github.com/Tencent/omi/commit/2163e38344d737c45abf2dcecf7a0521b088c9bd)

能说一下具体原理，挺好奇为什么会出现这种bug的

**Comment by dntzhang** [comment]
神坑。setData 里又触发了 observe， oberver callback 是异步的，上次的 callback 把 patch 清空了

**Comment by dntzhang** [comment]
所以改成 同步 就好了

**Comment by NidMo** [comment]
> 所以改成 同步 就好了

等于create()函数中，observer把微信原生的observer也覆盖了？然后obsever中有setData，setData又再次触发了observer导致出了问题？

**Comment by dntzhang** [comment]
不是

**Comment by dntzhang** [comment]
一言难尽

**Comment by shaobeichen** [comment]
我感觉到了坑

**Comment by dntzhang** [comment]
@LeachZhou 已经修了啊
