### ISSUE TITLE
真的没人觉得太麻烦了吗？

### ISSUE THREAD

**Issue by 0xwang-coder** [Tencent/westore#82]
作为一个刚开始写小程序的的后端，感觉用轮子比开发还麻烦，难道说页面之间的通信必须这么麻烦吗？PS：js小白

**Comment by dntzhang** [comment]
omix了解下 https://github.com/Tencent/omi/tree/master/packages/omix

**Comment by xiaojiaxi** [comment]
还是放弃了 哈哈哈哈

**Comment by Jerrodly** [comment]
我也觉得晦涩难懂，估计开发自己才懂得用

**Comment by 0xwang-coder** [comment]
> 还是放弃了 哈哈哈哈

当初也是觉得太麻烦，找了一个小众的开源插件[FlashEvent](https://github.com/wuyajun7/FlashEvent)，监听事件不需要先后顺序，可以看看

**Comment by 0xwang-coder** [comment]
> 我也觉得晦涩难懂，估计开发自己才懂得用

可能开发者当初的定位就是微信这种几亿流量级别的插件，我最后用的FlashEvent开源库

**Comment by dntzhang** [comment]
omix 内置的 mitt 可完全替代 flashevent 啊

**Comment by 0xwang-coder** [comment]
> omix 内置的 mitt 可完全替代 flashevent 啊

老大别生气，当初因为发现omix在后，先找到了falshevent解决了当时的问题，就没再尝试omix

**Comment by xiaojiaxi** [comment]
选择了用 [mobx-miniprogram-bindings](https://github.com/wechat-miniprogram/mobx-miniprogram-bindings) 和 navigateTo的 event

**Comment by dntzhang** [comment]
@wangwanchao  没有生气 :)
