### ISSUE TITLE
can't find module : ../../../utils/create.js

### ISSUE THREAD

**Issue by along0101** [Tencent/westore#87]
thirdScriptError 
 sdk uncaught third Error 
 can't find module : ../../../utils/create.js 
 Error: can't find module : ../../../utils/create.js
 目录中确实存在这个文件。就是有问题

**Comment by bili-jing** [comment]
用了bugout么

**Comment by along0101** [comment]
> 用了bugout么

没有使用bugout，就原来正常的，后来就一直提示这个错误
