### ISSUE TITLE
Array.prototype.size这段代码会导致整个js文件不能用

### ISSUE THREAD

**Issue by arsen2010** [Tencent/westore#9]
Array.prototype.size = function (length) {
        this.length = length;
    }

**Comment by dntzhang** [comment]
为什么？ @pageborn

**Comment by arsen2010** [comment]
我也觉得奇怪，js文件是异步用script标签引入的，引入后不完全执行，开始检查问题，发现把上面代码去掉就正常了，浏览器信息
navigator.userAgent
"Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36"
