### ISSUE TITLE
函数属性的正确使用方法

### ISSUE THREAD

**Issue by superbull** [Tencent/westore#97]
发现文档中对函数属性的使用方法没有描述得特别清楚，我用项目中的例子`/packages/westore`做了如下三个测试得到了不同的结果：

###  1. 对例子不做任何改动

> 现象：FullName的初始值没有显示，直到程序中更新`firtName`时才首次显示FullName

 ![westore1](https://user-images.githubusercontent.com/455630/63667430-408f4180-c806-11e9-936a-89041c0bf0fa.gif)

### 2. 注释掉例子中`pages/index/index.js`的本地`data`中的`firstName`和`lastName`
```javascript
create(store, {
  ...
  data: {
    motto: null,
    userInfo: null,
    hasUserInfo: null,
    canIUse: null,
    b: { arr: [ ] },
    // firstName: null,
    // lastName: null,
    pureProp: null,
    aaa: '私有数据，不放在store'
  },
  ...
}
```

> 现象：FullName永远不会显示

![westore2](https://user-images.githubusercontent.com/455630/63667723-69fc9d00-c807-11e9-8ae0-e998f505e7a8.gif)

### 3. 在页面`pages/index/index.js`上声明依赖的`fullName`函数属性
```javascript
create(store, {
  ...
  data: {
    motto: null,
    userInfo: null,
    hasUserInfo: null,
    canIUse: null,
    b: { arr: [ ] },
    // firstName: null,
    // lastName: null,
    fullName: null,
    pureProp: null,
    aaa: '私有数据，不放在store'
  },
  ...
}
```
> 现象：FullName正常显示并更新

![westore3](https://user-images.githubusercontent.com/455630/63667927-0d4db200-c808-11e9-8fb2-48c222e0b6da.gif)

**请问是否第3种才是正确的使用方法？**

**Comment by dntzhang** [comment]
对的。确实需要声明依赖。第三种写法正确。

**Comment by superbull** [comment]
好的，谢谢。需要我发个pull request修改一下文档和例子吗？

**Comment by dntzhang** [comment]
可以。欢迎，多谢
